### ISSUE TITLE
Maui crashes on login button clicked

### ISSUE THREAD

**Issue by emw1909** [IdentityModel/IdentityModel.OidcClient.Samples#151]
at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.Security.Authentication.Web.IWebAuthenticationBrokerStaticsMethods.AuthenticateAsync(IObjectReference _obj, WebAuthenticationOptions options, Uri requestUri, Uri callbackUri)
   at Windows.Security.Authentication.Web.WebAuthenticationBroker.AuthenticateAsync(WebAuthenticationOptions options, Uri requestUri, Uri callbackUri)
   at Microsoft.Maui.Authentication.WebAuthenticatorImplementation.<AuthenticateAsync>d__0.MoveNext()
   at MauiApp1.MauiAuthenticationBrowser.<InvokeAsync>d__0.MoveNext() in C:\Development\Research\IdentityModel.OidcClient.Samples-main\IdentityModel.OidcClient.Samples-main\Maui\MauiApp1\MauiApp1\MauiAuthenticationBrowser.cs:line 12
   at IdentityModel.OidcClient.AuthorizeClient.<AuthorizeAsync>d__4.MoveNext()
   at IdentityModel.OidcClient.OidcClient.<LoginAsync>d__9.MoveNext()
   at MauiApp1.MainPage.<OnLoginClicked>d__3.MoveNext() in C:\Development\Research\IdentityModel.OidcClient.Samples-main\IdentityModel.OidcClient.Samples-main\Maui\MauiApp1\MauiApp1\MainPage.xaml.cs:line 24

**Comment by frankbuckley** [comment]
I am seeing the same on Windows.

Possibly related?

- https://github.com/dotnet/maui/issues/2702
- https://github.com/microsoft/WindowsAppSDK/issues/441

**Comment by josephdecock** [comment]
Yes, we use the WebAuthenticator component from maui, which supports mobile platforms but not windows. The maui sample isn't meant to work as a windows app. It should work on iOS and android.
