### ISSUE TITLE
How to test with untrustred/insecure https 

### ISSUE THREAD

**Issue by tangkhaiphuong** [IdentityModel/IdentityModel.OidcClient.Samples#42]
I follow the example from https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/WinFormsWebView/SampleForm.cs#L39

My OAuth2 server is the demo and implements with https with untrusted/insecure. Then the exception is thrown:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Error loading discovery document: Error connecting to https://localhost:8080/.well-known/openid-configuration: An error occurred while sending the request.
  Source=IdentityModel.OidcClient
  StackTrace:
   at IdentityModel.OidcClient.OidcClient.<EnsureProviderInformationAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.OidcClient.OidcClient.<EnsureConfigurationAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.OidcClient.OidcClient.<LoginAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WinForms.SampleForm.<LoginButton_Click>d__3.MoveNext() in D:\Projects\IdentityModel.OidcClient.Samples\WinFormsWebView\SampleForm.cs:line 39

Inner Exception 1:
HttpRequestException: An error occurred while sending the request.

Inner Exception 2:
WinHttpException: A security error occurred
```

So how I configure OidcClient to ignore TSL/SSL secure authentication for demo only.

**Comment by superjulius** [comment]
I would also be interested to test it out using my local instance of Id Server and API.

I managed to get access to localhost (replacing with 10.0.2.2 that is used to access the local machine from the Android emulator) but now I am stuck with the default asp.net certificate.

I added the following line to allow accessing Id Server (which works) so I get the login page but the redirect does not work.

`ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;`
