### ISSUE TITLE
System.Net.WebException: NameResolutionFailure when clicking Call API after logged in, AndroidClientChromeCustomTabs.

### ISSUE THREAD

**Issue by PingPongSet** [IdentityModel/IdentityModel.OidcClient.Samples#54]
I got the error below and the app crashes when I clicked Call API button after logged in.
AndroidClientChromeCustomTabs on Android: 5.1

01-23 14:21:57.050 E/AndroidRuntime( 7529): Process: AndroidClientChromeCustomTabs.AndroidClientChromeCustomTabs, PID: 7529

01-23 14:21:57.050 E/AndroidRuntime( 7529): android.runtime.JavaProxyThrowable: System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: NameResolutionFailure

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Net.WebConnection+<Connect>d__16.MoveNext () [0x00044] in <3e9b3e26c4694baab3f689687ad40612>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529): --- End of stack trace from previous location where exception was thrown ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Net.WebConnection+<InitConnection>d__19.MoveNext () [0x000cc] in <3e9b3e26c4694baab3f689687ad40612>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529): --- End of stack trace from previous location where exception was thrown ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Net.WebOperation+<Run>d__57.MoveNext () [0x0009a] in <3e9b3e26c4694baab3f689687ad40612>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529): --- End of stack trace from previous location where exception was thrown ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Net.WebCompletionSource`1+<WaitForCompletion>d__15[T].MoveNext () [0x00094] in <3e9b3e26c4694baab3f689687ad40612>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529): --- End of stack trace from previous location where exception was thrown ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__241`1[T].MoveNext () [0x000c5] in <3e9b3e26c4694baab3f689687ad40612>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529): --- End of stack trace from previous location where exception was thrown ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <3e9b3e26c4694baab3f689687ad40612>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529): --- End of stack trace from previous location where exception was thrown ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x0041d] in <25ebe1083eaf4329b5adfdd5bbb7aa57>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529):    --- End of inner exception stack trace ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x00478] in <25ebe1083eaf4329b5adfdd5bbb7aa57>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529): --- End of stack trace from previous location where exception was thrown ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Net.Http.HttpClient+<SendAsyncWorker>d__49.MoveNext () [0x000ca] in <25ebe1083eaf4329b5adfdd5bbb7aa57>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529): --- End of stack trace from previous location where exception was thrown ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at AndroidClientChromeCustomTabs.MainActivity+<BtnCallApi_Click>d__4.MoveNext () [0x000af] in <6f4b2bd34dc847b9aa0a8fd843a7a215>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529): --- End of stack trace from previous location where exception was thrown ---

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <1219ce5aae934ab095dc0e05b2110050>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <1219ce5aae934ab095dc0e05b2110050>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <1219ce5aae934ab095dc0e05b2110050>:0 

01-23 14:21:57.050 E/AndroidRuntime( 7529):   at (wrapper dynamic-method) System.Object.5(intptr,intptr)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at android.os.Handler.handleCallback(Handler.java:739)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at android.os.Handler.dispatchMessage(Handler.java:95)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at android.os.Looper.loop(Looper.java:135)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at android.app.ActivityThread.main(ActivityThread.java:5256)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at java.lang.reflect.Method.invoke(Native Method)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at java.lang.reflect.Method.invoke(Method.java:372)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)

01-23 14:21:57.050 E/AndroidRuntime( 7529): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

01-23 14:21:57.057 W/ActivityManager(  753):   Force finishing activity 1 AndroidClientChromeCustomTabs.AndroidClientChromeCustomTabs/md598cf9e4c8d42422ef1da32861d686e66.MainActivity

**Comment by PingPongSet** [comment]
I found the problem:

The new url is https://demo.identityserver.io/api/test. so just change old one to that.

The old one being used is https://api.identityserver.io/, which is wrong.
