### ISSUE TITLE
Xamarin Forms: Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Context.startActivity(android.content.Intent, android.os.Bundle)' on a null object reference

### ISSUE THREAD

**Issue by godrage** [IdentityModel/IdentityModel.OidcClient.Samples#78]
When LoginAsync gets called I get the following exception:

`{Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Context.startActivity(android.content.Intent, android.os.Bundle)' on a null object reference
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
  at Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl (Android.Content.Context context, Android.Net.Uri url) [0x00053] in <d6a5756441fb4c68bac06bf8a8f33c0c>:0 
  at tBEE.Droid.ChromeCustomTabsBrowser.InvokeAsync (IdentityModel.OidcClient.Browser.BrowserOptions options) [0x0008b] in C:\Users\MAB\source\repos\tBEE\tBEE\tBEE.Android\ChromeCustomTabsBrowser.cs:96 
  at IdentityModel.OidcClient.AuthorizeClient+<AuthorizeAsync>d__4.MoveNext () [0x000ba] in C:\local\identity\model\IdentityModel.OidcClient\src\AuthorizeClient.cs:59 
--- End of stack trace from previous location where exception was thrown ---
  at IdentityModel.OidcClient.OidcClient+<LoginAsync>d__9.MoveNext () [0x000ee] in C:\local\identity\model\IdentityModel.OidcClient\src\OidcClient.cs:94 
--- End of stack trace from previous location where exception was thrown ---
  at tBEE.Views.AboutPage+<ConnectOData2>d__8.MoveNext () [0x0003e] in C:\Users\MAB\source\repos\tBEE\tBEE\tBEE\Views\AboutPage.xaml.cs:197 
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Context.startActivity(android.content.Intent, android.os.Bundle)' on a null object reference
	at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:143)
	at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

Since im pretty new to Xamarin Forms and Mobile Development I don't really know where to start with this kind of exception.

thanks in advance :)

**Comment by godrage** [comment]
Solved:

forgot to add "CrossCurrentActivity.Current.Init(this, savedInstanceState);"
to MainActivity.cs

my bad :*)
